### ISSUE TITLE
Misc typos

### ISSUE THREAD

**Issue by traviskorte** [aelkus/aelkus.github.io#1]
Enjoyed the piece but spotted a couple typos you can ctrl+F for. Forgive me if etiquette would dictate I fork+pull.

"an realization of Y socioeconomic power relation" -> "a realization"
"running amuck" -> "running amok"
"indifferent to safety purposes" -> wrong word?
"components of the algorithm that are being analyzed" -> "components of the algorithm are being analyzed"
"get rid out of all the spam" -> "get rid of all the spam"
"besides the point" -> "beside the point"
"an conversation about the way that adaptive programs and users collaboratively create outcomes" -> "a conversation"
"relationshop" -> relationship

**Comment by aelkus** [comment]
Heh. I'll correct those. Thanks!

**Comment by aelkus** [comment]
Side note: getting typo corrections in issues is pretty awesome.

**Comment by traviskorte** [comment]
Stole the idea from Eric Mill, who edited Ben Balter's blog the other day
in what I thought was an adorable display of friendship.
